mode: backtest
start_date: 2025-04-01
end_date: 2025-05-01
primary_interval: 1h
initial_cash: 100000
margin_requirement: 0.0
show_reasoning: true
show_agent_graph: true
signals:
  intervals: ["1h"]
  tickers: ["BTCUSDT"]
  strategies: ['MacdStrategy']
# , "RSIStrategy"]

